title: Hacker-Blog
description: "Blog for my CTFs and Cyber-Security challenges' writeups"
author:
  name: "Masrt200"
  email: "immasrt@gmail.com"
  url: "https://masrt200.github.io/hacker-blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Masrt200"
year : "2020"
